// Regenerates the redirect block in js/hubs.js from live Wikipedia.
//
// A link to "USA" is a link to United States, so closing a hub means closing
// every title that redirects to it. Those are fetched here and written into
// the source rather than looked up at race time: the board has to be the same
// for two people opening the same link, and it has to be there before the
// first article renders.
//
//   node tools/build-hubs.mjs          print what would change
//   node tools/build-hubs.mjs --write  write it into js/hubs.js
import { readFileSync, writeFileSync } from 'node:fs';
import { HUBS } from '../js/hubs.js';

const API = 'https://en.wikipedia.org/w/api.php';
const SOURCE = new URL('../js/hubs.js', import.meta.url);
const MARK_OPEN = '/* --- redirects: generated by tools/build-hubs.mjs --- */';
const MARK_CLOSE = '/* --- end redirects --- */';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// The anonymous API allows roughly ten requests in a burst. Thirty hubs with
// their continuations is well past that, so back off rather than fall over
// half way through and write a truncated board.
async function api(params) {
  const url = new URL(API);
  url.search = new URLSearchParams({ format: 'json', formatversion: '2', origin: '*', ...params }).toString();
  for (let attempt = 0; ; attempt += 1) {
    // Wikipedia throttles anonymous traffic that does not say who it is much
    // harder than traffic that does.
    const res = await fetch(url, {
      headers: { 'User-Agent': 'wiki-game-build-hubs/1.0 (https://github.com/chriswolfesq-collab/wikigame)' }
    });
    if (res.ok) return res.json();
    if (attempt >= 4 || ![429, 502, 503, 504].includes(res.status)) {
      throw new Error(`${res.status} ${res.statusText}`);
    }
    await sleep(1000 * 2 ** attempt);
  }
}


// Every hub must be a real article and the canonical one: a hub that is itself
// a redirect would close the wrong page and miss the one it meant.
const check = await api({
  action: 'query', redirects: '1', prop: 'pageprops', ppprop: 'disambiguation',
  titles: HUBS.join('|')
});
for (const r of check.query?.redirects || []) throw new Error(`hub is a redirect: ${r.from} -> ${r.to}`);
for (const p of check.query?.pages || []) {
  if (p.missing) throw new Error(`hub does not exist: ${p.title}`);
  if (p.pageprops && 'disambiguation' in p.pageprops) throw new Error(`hub is a disambiguation page: ${p.title}`);
}

const redirects = {};
let total = 0;
for (const hub of HUBS) {
  const names = [];
  let cont = null;
  do {
    const data = await api({
      action: 'query', titles: hub, prop: 'redirects',
      rdnamespace: '0', rdlimit: 'max', ...(cont ? { rdcontinue: cont } : {})
    });
    names.push(...(data.query?.pages?.[0]?.redirects || []).map((r) => r.title));
    cont = data.continue?.rdcontinue || null;
  } while (cont);
  // Every one of them, not a selection. Any rule for picking the "real" ones
  // is a guess about how articles are written, and a redirect left out is a
  // link that looks live and is not.
  redirects[hub] = names.sort((a, b) => a.localeCompare(b));
  total += names.length;
  console.error(`${hub}: ${names.length}`);
  await sleep(400);
}

const body = HUBS.map(
  (hub) => `  ${JSON.stringify(hub)}: [\n${redirects[hub].map((r) => `    ${JSON.stringify(r)}`).join(',\n')}\n  ]`
).join(',\n');
const block = `${MARK_OPEN}\nconst REDIRECTS = {\n${body}\n};\n${MARK_CLOSE}`;

console.error(`\n${total} redirects across ${HUBS.length} hubs, ${(block.length / 1024).toFixed(1)} KB`);

const source = readFileSync(SOURCE, 'utf8');
const start = source.indexOf(MARK_OPEN);
const end = source.indexOf(MARK_CLOSE);
const next =
  start >= 0 && end > start
    ? source.slice(0, start) + block + source.slice(end + MARK_CLOSE.length)
    : `${source.trimEnd()}\n\n${block}\n`;

if (process.argv.includes('--write')) {
  writeFileSync(SOURCE, next);
  console.error('written to js/hubs.js');
} else {
  console.error(next === source ? 'no change' : 'would change js/hubs.js (pass --write)');
}
